version: "3.9"

services:
  sp-backend:
    build:
      context: .         # repo root
      dockerfile: backend/Dockerfile

    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  sp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
